name: PROD CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'docker-compose.dev.yml'
      - 'build_*.sh'
      - 'proto/**'
      - 'migrate.Dockerfile'
      - 'cmd/**'
      - 'configs/**'
      - 'internal/**'
      - 'migrations/**'
jobs:
  build_backend:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Debug
        run: |
          echo "github.ref -> {{ github.ref }}"

      - name: Build proto
        run: make pb

  push-backend:
    runs-on: ubuntu-22.04
    needs: ['build_backend']
    env:
      IMG_NAME: 'warehouse-auth'
      IMG_REGISTRY: 'registry.warehousai.com'

    steps:
      - uses: actions/checkout@v3
      - name: Load metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMG_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value={{sha}},enable=${{ github.ref_type != 'tag' }}

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          registry: registry.warehousai.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: '{{defaultContext}}'

          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: '${{env.IMG_REGISTRY}}/${{ env.IMG_NAME }}:latest'
          labels: ${{ steps.metadata.outputs.labels }}
